server:
  port: 7777

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing
    username: postgres
    password: pawel1
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

logging:
  level:
    pl:
      futurecollars:
        invoicing:

invoicing-system:
  database: memory