invoicing-system:
  database: file
  database.dbDirectory: db
  database.idFileNameForInvoices: db-ids-invoice
  database.dataFileNameForInvoices: db-data-invoice
  database.idFileNameForCompany: db-ids-company
  database.dataFileNameForCompany: db-data-company