package pl.futurecollars.invoicing.model;

import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import pl.futurecollars.invoicing.db.WithId;

@Entity(name = "companies")
@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
public class Company implements WithId {

    @ApiModelProperty(value = "Company id (generated by application)", example = "1", hidden = true)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @EqualsAndHashCode.Exclude
    private Long id;

    @ApiModelProperty(value = "Tax identification number", required = true, example = "421-896-78-55")
    @Column(name = "tax_identification_number")
    private String taxIdentificationNumber;

    @ApiModelProperty(value = "Company address", required = true, example = "377 Ohio Road Pulo")
    private String address;

    @ApiModelProperty(value = "Company name", required = true, example = "Voolith")
    private String name;

    @ApiModelProperty(value = "Health insurance", required = true, example = "500")

    private BigDecimal healthInsurance;

    @ApiModelProperty(value = "Pension insurance", required = true, example = "400")
    private BigDecimal pensionInsurance;

    public Company(String taxIdentificationNumber, String address, String name, BigDecimal healthInsurance, BigDecimal pensionInsurance) {
        this.taxIdentificationNumber = taxIdentificationNumber;
        this.address = address;
        this.name = name;
        this.healthInsurance = healthInsurance;
        this.pensionInsurance = pensionInsurance;
    }

    public static Company copyOf(Company company, boolean idNull) {
        return Company.builder()
            .id(idNull ? null : company.getId())
            .taxIdentificationNumber(company.getTaxIdentificationNumber())
            .address(company.getAddress())
            .name(company.getName())
            .healthInsurance(company.getHealthInsurance())
            .pensionInsurance(company.getPensionInsurance())
            .build();
    }
}
