package pl.futurecollars.invoicing.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Entity(name = "companies")
@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
public class Company {

    @ApiModelProperty(value = "Company id (generated by application)", required = true, example = "1")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonIgnore
    @EqualsAndHashCode.Exclude
    private Integer id;

    @ApiModelProperty(value = "Tax identification number", required = true, example = "421-896-78-55")
    private String taxIdentificationNumber;

    @ApiModelProperty(value = "Company address", required = true, example = "377 Ohio Road Pulo")
    private String address;

    @ApiModelProperty(value = "Company name", required = true, example = "Voolith")
    private String name;

    @ApiModelProperty(value = "Health insurance", required = true, example = "500")
    private BigDecimal healthInsurance;

    @ApiModelProperty(value = "Pension insurance", required = true, example = "400")
    private BigDecimal pensionInsurance;

    public Company(String taxIdentificationNumber, String address, String name, BigDecimal healthInsurance, BigDecimal pensionInsurance) {
        this.taxIdentificationNumber = taxIdentificationNumber;
        this.address = address;
        this.name = name;
        this.healthInsurance = healthInsurance;
        this.pensionInsurance = pensionInsurance;
    }
}
