name: CI

on:
  push:
    branches: [ task-2-continue-config-and-write-code ]
  pull_request:
    branches: [ task-2-continue-config-and-write-code ]
workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: '14'
    - name: Build with Gradle
      run: ./gradlew build
